/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logRPC.h"

bool_t
xdr_log_args (XDR *xdrs, log_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->usuario, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_log_attach_args (XDR *xdrs, log_attach_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->usuario, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fichero, 256))
		 return FALSE;
	return TRUE;
}
