/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "logRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_operacion_1(log_args arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOG_OPERACION,
		(xdrproc_t) xdr_log_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
log_sendattach_1(log_attach_args arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOG_SENDATTACH,
		(xdrproc_t) xdr_log_attach_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
