/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGRPC_H_RPCGEN
#define _LOGRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct log_args {
	char *usuario;
	char *operacion;
};
typedef struct log_args log_args;

struct log_attach_args {
	char *usuario;
	char *fichero;
};
typedef struct log_attach_args log_attach_args;

#define LOG_PROG 0x20000002
#define LOG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERACION 1
extern  enum clnt_stat log_operacion_1(log_args , int *, CLIENT *);
extern  bool_t log_operacion_1_svc(log_args , int *, struct svc_req *);
#define LOG_SENDATTACH 2
extern  enum clnt_stat log_sendattach_1(log_attach_args , int *, CLIENT *);
extern  bool_t log_sendattach_1_svc(log_attach_args , int *, struct svc_req *);
extern int log_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERACION 1
extern  enum clnt_stat log_operacion_1();
extern  bool_t log_operacion_1_svc();
#define LOG_SENDATTACH 2
extern  enum clnt_stat log_sendattach_1();
extern  bool_t log_sendattach_1_svc();
extern int log_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_args (XDR *, log_args*);
extern  bool_t xdr_log_attach_args (XDR *, log_attach_args*);

#else /* K&R C */
extern bool_t xdr_log_args ();
extern bool_t xdr_log_attach_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGRPC_H_RPCGEN */
